Traceback (most recent call last):
  File "/home/andrew/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/andrew/.local/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/andrew/.local/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/andrew/.local/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/andrew/.local/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/andrew/.local/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/andrew/.local/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.close(fig1)
plt.close('all')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Input [0;32mIn [6][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [43mplt[49m[38;5;241;43m.[39;49m[43mclose[49m[43m([49m[43mfig1[49m[43m)[49m
[1;32m      2[0m plt[38;5;241m.[39mclose([38;5;124m'[39m[38;5;124mall[39m[38;5;124m'[39m)

File [0;32m/usr/lib/python3/dist-packages/matplotlib/pyplot.py:690[0m, in [0;36mclose[0;34m(fig)[0m
[1;32m    688[0m         _pylab_helpers[38;5;241m.[39mGcf[38;5;241m.[39mdestroy(num)
[1;32m    689[0m [38;5;28;01melif[39;00m [38;5;28misinstance[39m(fig, Figure):
[0;32m--> 690[0m     [43m_pylab_helpers[49m[38;5;241;43m.[39;49m[43mGcf[49m[38;5;241;43m.[39;49m[43mdestroy_fig[49m[43m([49m[43mfig[49m[43m)[49m
[1;32m    691[0m [38;5;28;01melse[39;00m:
[1;32m    692[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([38;5;124m"[39m[38;5;124mclose() argument must be a Figure, an int, a string, [39m[38;5;124m"[39m
[1;32m    693[0m                     [38;5;124m"[39m[38;5;124mor None, not [39m[38;5;124m'[39m[38;5;132;01m%s[39;00m[38;5;124m'[39m[38;5;124m"[39m)

File [0;32m/usr/lib/python3/dist-packages/matplotlib/_pylab_helpers.py:64[0m, in [0;36mGcf.destroy_fig[0;34m(cls, fig)[0m
[1;32m     61[0m num [38;5;241m=[39m [38;5;28mnext[39m((manager[38;5;241m.[39mnum [38;5;28;01mfor[39;00m manager [38;5;129;01min[39;00m [38;5;28mcls[39m[38;5;241m.[39mfigs[38;5;241m.[39mvalues()
[1;32m     62[0m             [38;5;28;01mif[39;00m manager[38;5;241m.[39mcanvas[38;5;241m.[39mfigure [38;5;241m==[39m fig), [38;5;28;01mNone[39;00m)
[1;32m     63[0m [38;5;28;01mif[39;00m num [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[0;32m---> 64[0m     [38;5;28;43mcls[39;49m[38;5;241;43m.[39;49m[43mdestroy[49m[43m([49m[43mnum[49m[43m)[49m

File [0;32m/usr/lib/python3/dist-packages/matplotlib/_pylab_helpers.py:53[0m, in [0;36mGcf.destroy[0;34m(cls, num)[0m
[1;32m     51[0m manager [38;5;241m=[39m [38;5;28mcls[39m[38;5;241m.[39mfigs[num]
[1;32m     52[0m manager[38;5;241m.[39mcanvas[38;5;241m.[39mmpl_disconnect(manager[38;5;241m.[39m_cidgcf)
[0;32m---> 53[0m [38;5;28;43mcls[39;49m[38;5;241;43m.[39;49m[43m_activeQue[49m[38;5;241;43m.[39;49m[43mremove[49m[43m([49m[43mmanager[49m[43m)[49m
[1;32m     54[0m [38;5;28;01mdel[39;00m [38;5;28mcls[39m[38;5;241m.[39mfigs[num]
[1;32m     55[0m manager[38;5;241m.[39mdestroy()

[0;31mValueError[0m: list.remove(x): x not in list
ValueError: list.remove(x): x not in list

